apiVersion: v1
kind: Service
metadata:
  labels:
    run: conduit-frontend
  name: conduit-frontend
spec:
  ports:
    - name: conduit
      port: 4100
      protocol: TCP
      targetPort: 4100
  selector:
    run: conduit-frontend
  type: NodePort
